---
name: Empty build matrix

on:
  workflow_dispatch:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    steps:
      - name: Checkout current repository to get the matrix file
        uses: actions/checkout@v3

      - name: Generate the build matrix
        id: gen-matrix
        run: |
          matrix=$(cat ${GITHUB_WORKSPACE}/build-matrix-empty.json)
          echo "::set-output name=matrix::${matrix}"

  log-matrix:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    if: ${{ fromJson(needs.build-matrix.outputs.matrix).include[0] }}
    steps:
      - run: echo ${{ matrix.versions.kernel }}
